config/routes.rb
Autotest::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  namespace :admin do
    resources :beta_invitations, only: [:index] do
      member do
        post 'invite'
      end
    end
  end

  get "/recorder" => "recorder#index"
  get "/developer" => "recorder#developer"


  namespace :heroku do
    resources :resources
    post '/sso/login' => "sso#create"
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount MailPreview => 'mail_view' if Rails.env.development?

  resources :scenarios
  resources :plans do
    member do
      get :upgrade
      post :upgrade
      post :downgrade
    end
  end
  resources :credit_cards, only: [:index, :create, :destroy], path: "credit-cards" do
    member do
      post :default
    end
  end
  resources :messages do
    member do
      post :mark_read
    end
    collection do
      post :mark_all_read
    end
  end

  post "/send-developer-emails" => "pages#send_developer_emails", as: "send_developer_emails"

  get "/tours" => "tours#show"
  put "/tours" => "tours#update"

  #application
  devise_for :users, controllers: {registrations: :registrations, sessions: :sessions, omniauth_callbacks: :omniauth_callbacks, passwords: :passwords}, skip: :invitations
  devise_scope :user do
    get "/login" => "sessions#new"
    get "/logout" => "sessions#destroy"
    get '/sign-up-free' => 'registrations#new', as: 'sign_up_free'
    get '/my-info' => 'registrations#edit', as: 'my_info'
    get '/change-your-plan' => 'registrations#change_plan', as: 'change_plan'
    post "/upgrade/:plan_id" => 'registrations#upgrade', as: 'upgrade'
    get '/upgrade/:plan_id' => "registrations#upgrade", as: "get_upgrade"
    get '/downgrade/:plan_id' => "registrations#downgrade", as: "get_downgrade"
    get '/manage-billing' => 'registrations#manage_billing', as: 'billing'
    get '/users/confirm' => "confirmations#show", as: 'confirmation'
    post '/cancel' => "registrations#cancel_user", as: "cancel"
  end

  get 'dashboard', to: "dashboard#index"

  as :user do
    get 'invitations', to: 'invitations#index', as: 'invitations'
    get 'invitation', to: "invitations#new", as: :new_invitation
    post 'invitation', to: "invitations#create"
    get 'invitation/accept', to: "invitations#edit", as: :accept_invitation
    put 'invitation/accept', to: "invitations#update", as: :complete_invitation
  end

  resources :projects do
    post 'remove_user/:user_id', to: 'projects#remove_user', on: :member, as: :remove_user
    post 'verify_script', to: 'projects#verify_script', as: :verify_script
    post 'update_notifications', to: "projects#update_notifications", on: :member, as: :update_notifications
    put 'add_owner/:user_id', to: 'projects#add_owner', as: :add_owner
    put 'remove_owner/:user_id', to: 'projects#remove_owner', as: :remove_owner
    post :run, on: :member
    resources :test_runs, controller: :project_test_runs, only: [:index, :show]
    resources :tests, controller: :scenarios do
      post :run, on: :member, as: "run_scenario"
      resources :steps
      resources :test_runs, only: [:index, :show]
    end
  end

  namespace :api do
    namespace :v1 do
      match '/scenarios' => "scenarios#create", via: :options
      match '/scenarios/:scenario_id' => "scenarios#show", via: :options
      match '/scenarios/:scenario_id/steps' => "steps#create", via: :options
      match '/scenarios/:scenario_id/publish' => "scenarios#publish", via: :options
      match '/scenarios/:scenario_id/publish' => "scenarios#publish", via: :post
      resources :scenarios do
        resources :steps
      end
    end

    namespace :dashing do
      match '/total_tests_run' => "dashboard#total_tests_run", via: :get
      match '/total_minutes' => "dashboard#total_minutes", via: :get
    end
  end

  #pages
  get 'faqs', to: 'pages#faqs'
  get 'pricing', to: 'pages#pricing'
  get 'documentation', to: 'pages#documentation'
  # get 'privacy', to: 'pages#privacy'
  get 'terms', to: 'pages#terms'
  get 'beta-invitation', to: 'pages#beta_invitation', as: 'beta_invitation'
  post 'create-beta-invitation', to: 'pages#create_beta_invitation', as: 'create_beta_invitation'
  post '/coupons/redeem', to: "coupons#redeem", as: "redeem_coupon"

  # Test Pages
  get '/test/index', to: "autotest#index"
  get '/test/form', to: "autotest#form", as: "test_form"
  post '/test/form_post', to: "autotest#form_post", as: "test_form_post"
  get '/test/thankyou', to: "autotest#thankyou", as: "test_thankyou"
  get '/test/terms', to: "autotest#terms", as: 'test_terms'

  root 'pages#welcome'
end

app/controllers/autotest_controller.rb
class AutotestController < ApplicationController

  layout 'test'

  before_filter :find_project

  skip_before_filter :http_basic_authenticate

	def index; end

	def form
    @project_id = params[:project_id]
  end

	def form_post
    flash.now[:error] = ""
    if params[:name].blank?
      flash.now[:error] += "Please fill out your name. "
    end
    if params[:password] != params[:password_confirmation]
      flash.now[:error] += "Your passwords do not match."
    end

    if flash.now[:error].blank?
      session[:autotest_signup] = params
      redirect_to test_thankyou_path(project_id: params[:project_id])
    else
      render 'form', location: test_form_path(project_id: params[:project_id])
    end
	end

  def thankyou; end

  def terms; end

  private

    def find_project
      @project = Project.find(params[:project_id])
    end


end

app/helpers/autotest_helper.rb
module AutotestHelper
end

app/views/autotest/_add_new_feature.html.haml
%div#create-feature-modal.modal.fade
  %div.modal-content
    %div.modal-header
      %button.close{data: {dismiss: "modal"}} &times;
      %h4 Create a new Feature
    %div.modal-body
      %label Feature Name
      %input{type: "text", name: "feature[name]", id: "feature_name"}
    %div.modal-footer
      %button.btn.btn-default{data: {dismiss: "modal"}} Close
      %button.btn.btn-info#create-feature{"disabled" => "disabled"} Create Feature

app/views/autotest/_text_highlight.html.haml
%button#start-text-highlight.btn.btn-primary{style: "display: none;"}
  %span.glyphicon.glyphicon-screenshot
  Validate Page
%button#stop-record-text-highlight.btn.btn-danger{style: "display: none;"} Stop Recording Elements

app/views/autotest/form.html.haml
.col-md-6
  %h1 Test Signup Form
  = form_tag(test_form_post_path(project_id: @project_id), class: 'test-form') do
    = label_tag("Name* (required)")
    = text_field_tag("name", nil, class: 'form-control')
    %br
    = label_tag("email")
    = email_field_tag("email", nil, class: 'form-control')
    %br
    = label_tag("password")
    = password_field_tag("password", nil, class: 'form-control')
    %br
    = label_tag("password_confirmation")
    = password_field_tag("password_confirmation", nil, class: 'form-control')
    %br
    = label_tag("company")
    = text_field_tag("company", nil, class: "form-control")
    %br
    = label_tag("plan")
    = select_tag("plan", options_for_select([["Free $0/monthly",1], ["Plus $19.99/monthly", 2]]))
    %br
    = label_tag("mailing_list")
    = radio_button_tag("mailing_list", "y", false)
    Yes
    = radio_button_tag("mailing_list", "n", false)
    No
    %br
    = check_box_tag("terms_and_conditions")
    = label_tag("terms_and_conditions", "I Accept Terms and Conditions")
    (
    = link_to("View Terms and Conditions", test_terms_path(project_id: @project.id))
    )
    %br
    = submit_tag("Save", class: 'btn btn-default btn-info', style: "background-color: #428bca")
.col-md-1
.col-md-5
  #sample-intro
    %h1 Sample Project
    %p This is just a sample project.  Take a few minutes to explore, record a few tests, and watch them run in developer mode.

  #sample-trivia
    %h1 Gorilla Trivia
    %p If you were taking a casual stroll through the jungle and bumped into King Kong, you shouldn't be afraid to pet him because:
    %span#trivia-answer __________ ?
    %button#trivia-answer-button Tell me the answer!

  #sample-select
    %h1 Purchase an Ape
    %select#selected-ape
      %option{ selected: 'selected', disabled: true } Choose one
      %option{ value: 'Gorilla' } Gorilla
      %option{ value: 'Chimpanzee' } Chimpanzee
      %option{ value: 'Baboon' } Baboon
      %option{ value: 'Grape Ape' } Grape Ape
    %br
    %button#purchase-ape Put In Shopping Cart

  #sample-shopping-cart
    %h3 Shopping Cart
    #ape-bin


#tour-sample-project{style: "position: absolute; top: 40%; left: 60%;"}
#tour-verify-presence{style: "position: absolute; top: 50%; left: 60%;"}
#tour-create-test{style: "position: absolute; top: 40%; left: 60%;"}

%ol.joyride-tour#sample-project-tour
  %li{data: {id: "tour-sample-project", button: 'Next'}}
    %h3 Sample Project
    %p
      This here is the sample project we've been running tests on. This is the last part of the tour! Once you've created a test of your own, you'll have experienced it all.
      %i
        warning: mastering GorillaTest does not prepare you for interaction with real live Gorillas.
  %li{data: {id: "tour-verify-presence", button: 'Next'}}
    %h3 "Verify Presence" huh?
    %p Once you start recording you'll see a "Verify Presence" button. What is this for you may ask? You can use this to select elements on the page that you would like the GorillaTest to verify the presence of. This can come in handy to make sure the correct things happen when buttons are pressed. Try using this with the Gorilla Trivia or Gorilla Store on this page.
  %li{data: {id: "tour-create-test"}}
    %h3 You're The Smartest Primate In The Room
    %p We've taught you all we know! Now less talking and more recording!

app/views/autotest/index.html.haml
= link_to "Form Page", test_form_path

app/views/autotest/terms.html.haml
.container
  .row
    .col-sm-12
      %h1 Terms and Conditions

      %h3 Terms
      %p
        Yolo ipsum dolor sit amet, consectetur adipiscing elit. Ut ac Gorilla leo. Carpe diem vulputate est nec commodo rutrum. Pellentesque mattis convallis nisi eu and I ain’t stoppin until the swear jar’s full. Ut Gorilla velit at mauris interdum, fringilla dictum neque rutrum. Curabitur mattis odio at erat viverra lobortis. Poppin’ bottles on the ice, tristique suscipit mauris elementum tempus. Quisque ut felis vitae elit tempor interdum viverra a est. Drop it like it’s hot, at pretium quam. In nec scelerisque purus. Nam dignissim lacus ipsum, a ullamcorper nulla pretium non. Aliquam sed enim faucibus, pulvinar felis at, vulputate augue. Ten, ten, twenties on them fifties, trick, at tempus libero fermentum id. Vivamus ut nisi dignissim, condimentum urna vel, dictum massa. Donec justo yolo, rutrum vitae dui in, dapibus tempor Gorilla. I do it big. Fusce ut sagittis mi.

      %h3 Privacy
      %p
        Donec accumsan consectetur faucibus. YOLO, you only live once. Donec eget semper eros. Vestibulum lobortis eros vel elementum suscipit. Nunc tempus lectus elit, et faucibus ligula dignissim nec. Phasellus in turpis porta, laoreet sapien vitae, auctor ante.  Your chick, she so Gorilla, nec consequat dui imperdiet eget. In quis rhoncus sem, eu eleifend purus. Etiam sodales turpis volutpat ultricies blandit. #Swaggityswag Donec pretium tincidunt mi, id semper dolor commodo eget.

      %h3 Agreement
      %p
        Don’t trust anyone, cause you only live once. Aliquam imperdiet, ligula vehicula sodales Test, dui arcu ultricies libero, vitae tempor eros libero sed neque. Pop a molly, I’m sweatin’, consequat feugiat eros.  How you like your eggs, fried or fertilized? Mi ullamcorper molestie vehicula, nulla est hendrerit ante, eget tempor augue felis ut velit. Sed ut tortor nibh. Phasellus et erat a nisl molestie tempor et at mi. I’m ballin’ hard, I need a jersey on, sollicitudin eget auctor quis, aliquet vitae Gorilla.

app/views/autotest/thankyou.html.haml
.col-md-4.col-md-offset-4
  %h1
    Thanks!
  %p
    Thank you Demo User for submitting our test form. Click #{link_to "here", test_form_path(project_id: params[:project_id])} to go back to the form!