config/routes.rb
Autotest::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  namespace :admin do
    resources :beta_invitations, only: [:index] do
      member do
        post 'invite'
      end
    end
  end

  get "/recorder" => "recorder#index"
  get "/developer" => "recorder#developer"


  namespace :heroku do
    resources :resources
    post '/sso/login' => "sso#create"
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount MailPreview => 'mail_view' if Rails.env.development?

  resources :scenarios
  resources :plans do
    member do
      get :upgrade
      post :upgrade
      post :downgrade
    end
  end
  resources :credit_cards, only: [:index, :create, :destroy], path: "credit-cards" do
    member do
      post :default
    end
  end
  resources :messages do
    member do
      post :mark_read
    end
    collection do
      post :mark_all_read
    end
  end

  post "/send-developer-emails" => "pages#send_developer_emails", as: "send_developer_emails"

  get "/tours" => "tours#show"
  put "/tours" => "tours#update"

  #application
  devise_for :users, controllers: {registrations: :registrations, sessions: :sessions, omniauth_callbacks: :omniauth_callbacks, passwords: :passwords}, skip: :invitations
  devise_scope :user do
    get "/login" => "sessions#new"
    get "/logout" => "sessions#destroy"
    get '/sign-up-free' => 'registrations#new', as: 'sign_up_free'
    get '/my-info' => 'registrations#edit', as: 'my_info'
    get '/change-your-plan' => 'registrations#change_plan', as: 'change_plan'
    post "/upgrade/:plan_id" => 'registrations#upgrade', as: 'upgrade'
    get '/upgrade/:plan_id' => "registrations#upgrade", as: "get_upgrade"
    get '/downgrade/:plan_id' => "registrations#downgrade", as: "get_downgrade"
    get '/manage-billing' => 'registrations#manage_billing', as: 'billing'
    get '/users/confirm' => "confirmations#show", as: 'confirmation'
    post '/cancel' => "registrations#cancel_user", as: "cancel"
  end

  get 'dashboard', to: "dashboard#index"

  as :user do
    get 'invitations', to: 'invitations#index', as: 'invitations'
    get 'invitation', to: "invitations#new", as: :new_invitation
    post 'invitation', to: "invitations#create"
    get 'invitation/accept', to: "invitations#edit", as: :accept_invitation
    put 'invitation/accept', to: "invitations#update", as: :complete_invitation
  end

  resources :projects do
    post 'remove_user/:user_id', to: 'projects#remove_user', on: :member, as: :remove_user
    post 'verify_script', to: 'projects#verify_script', as: :verify_script
    post 'update_notifications', to: "projects#update_notifications", on: :member, as: :update_notifications
    put 'add_owner/:user_id', to: 'projects#add_owner', as: :add_owner
    put 'remove_owner/:user_id', to: 'projects#remove_owner', as: :remove_owner
    post :run, on: :member
    resources :test_runs, controller: :project_test_runs, only: [:index, :show]
    resources :tests, controller: :scenarios do
      post :run, on: :member, as: "run_scenario"
      resources :steps
      resources :test_runs, only: [:index, :show]
    end
  end

  namespace :api do
    namespace :v1 do
      match '/scenarios' => "scenarios#create", via: :options
      match '/scenarios/:scenario_id' => "scenarios#show", via: :options
      match '/scenarios/:scenario_id/steps' => "steps#create", via: :options
      match '/scenarios/:scenario_id/publish' => "scenarios#publish", via: :options
      match '/scenarios/:scenario_id/publish' => "scenarios#publish", via: :post
      resources :scenarios do
        resources :steps
      end
    end

    namespace :dashing do
      match '/total_tests_run' => "dashboard#total_tests_run", via: :get
      match '/total_minutes' => "dashboard#total_minutes", via: :get
    end
  end

  #pages
  get 'faqs', to: 'pages#faqs'
  get 'pricing', to: 'pages#pricing'
  get 'documentation', to: 'pages#documentation'
  # get 'privacy', to: 'pages#privacy'
  get 'terms', to: 'pages#terms'
  get 'beta-invitation', to: 'pages#beta_invitation', as: 'beta_invitation'
  post 'create-beta-invitation', to: 'pages#create_beta_invitation', as: 'create_beta_invitation'
  post '/coupons/redeem', to: "coupons#redeem", as: "redeem_coupon"

  # Test Pages
  get '/test/index', to: "autotest#index"
  get '/test/form', to: "autotest#form", as: "test_form"
  post '/test/form_post', to: "autotest#form_post", as: "test_form_post"
  get '/test/thankyou', to: "autotest#thankyou", as: "test_thankyou"
  get '/test/terms', to: "autotest#terms", as: 'test_terms'

  root 'pages#welcome'
end

app/models/project.rb
require 'nokogiri'

class Project

  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paranoia
  include Mongoid::Slug

  field :name, type: String
  field :url, type: String
  field :status, type: String
  field :api_key, type: String
  field :script_verified, type: Boolean, default: false
  field :email_notification, type: String, default: "success"
  field :basic_auth_username, type: String
  field :basic_auth_password, type: String
  field :demo_project, type: Boolean, default: false

  slug :name

  belongs_to :user

  alias :creator :user

  has_many :scenarios
  has_many :project_users, dependent: :destroy
  has_many :test_runs, class_name: 'ProjectTestRun', dependent: :destroy

  embeds_many :secondary_domains, class_name: 'SecondaryDomain'

  validates :name, presence: true, uniqueness: {scope: :user}

  validates :url, presence: true, url: true

  before_create :add_auth_key

  embeds_many :notifications

  # Figure out how to do the project /user relationships
  # user has_and_belongs_to_many projects / teams. - jkr


  def post_notifications(message)
    notifications.each do |notification|
      notification.speak(message)
    end
  end

  def base_url(scheme)
    base_url = "#{scheme}://#{host}"
    if [80,443].include?(port)
      return base_url
    else
      return "#{base_url}:#{port}"
    end
  end

  def has_invitations_left?
    creator.plan.num_users > users.count
  end

  def num_invitations_remaining
    creator.plan.num_users - users.count
  end

  def users
    users = User.in(id: project_users.map(&:user_id)).all
    return users.to_a
  end

  def owners
    pu_owners = project_users.select { |pu| pu.user if pu.rights == 'owner' }
    pu_owners.map(&:user)
  end

  def owner?(user)
    owners.include?(user)
  end

  def script_present?
    search_for_script
  end

  def all_test_runs
    (test_runs + scenarios.map{|s| s.test_runs}).flatten.sort_by(&:created_at).reverse
  end

  def num_passed_tests
    all_test_runs.select{|t| t.status == "pass"}.count
  end

  def num_failed_tests
    all_test_runs.select{|t| t.status == "fail"}.count
  end

  def num_running_tests
    all_test_runs.select{|t| t.status != "running"}.count
  end

  private

  def port
    URI.parse(url).port
  end

  # def scheme
  #   URI.parse(url).scheme
  # end

  def host
    URI.parse(url).host
  end

  # Add specs for this.
  def search_for_script
    # Can't have a hard coded script source:
    autotest_script_source = "#{ENV['API_URL']}/assets/recordv2.js"
    # Need to add a rescue, open will throw an exception if it can't open the URL

    begin
      if !self.basic_auth_username.blank?
        auth = {username: self.basic_auth_username, password: self.basic_auth_password}
        response = HTTParty.get(url, basic_auth: auth)
      else
        response = HTTParty.get(url)
      end

      document = Nokogiri::HTML(response.body)
      document.search("script").detect do |script|
        if script.attributes["src"] && script.attributes["src"].value.include?(autotest_script_source)
          return project_script_valid?(script)
        end
      end
    rescue Exception => e
      Rails.logger.debug("error is #{e.inspect}")
      return false
    end
  end

  def project_script_valid?(script)
    attrs = []
    attrs << script.attributes['data-api-key'].value
    attrs << script.attributes['data-project-id'].value
    return attrs.sort == [api_key, id.to_s].sort
  end

  def add_auth_key
    self.api_key = SecureRandom.hex
  end

end

app/controllers/api/v1/projects_controller.rb
class Api::V1::ProjectsController < Api::V1::BaseController

  respond_to :json, :js

  skip_before_filter :restrict_access

  def index
    @projects = [@current_project]
    respond_with(@projects)
  end

  def show
    @project = current_project
    respond_with(@project)
  end

  def play
    @project = Project.where({api_key: params[:api_key]})
    test_run = @project.test_runs.build({user: current_user, platforms: params[:browsers]})
    if test_run.save
      test_run.platforms.each do |p|
        browser_test = test_run.browser_tests.create!({browser: p.split('_').last,
                                              platform: p.split('_').first})
      end
      TestWorker.perform_async("queue_tests", "Project", test_run.id.to_s)
    end
    respond_with("OK")
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :authenticate_user!
  before_filter :find_project, except: [:index, :new, :create]
  before_filter :get_concurrency_limit, only: [:index, :show]
  before_filter :ensure_num_projects_limit, only: [:create]

  def index
    @projects = current_user.projects
  end

  def show
    @scenarios = @project.scenarios.all.sort_by(&:created_at).reverse
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id
    if @project.save
      @project_user = ProjectUser.create!({user_id: current_user.id, project_id: @project.id, rights: 'owner'})
      respond_to do |format|
        format.html { redirect_to project_path(@project) }
      end
    else
      respond_to do |format|
        format.html { render :new, alert: "Project could not be created." }
      end
    end
  end

  def edit
    if @project.notifications.any?
      @notification = @project.notifications.first
    else
      @notification = @project.notifications.build
    end
  end

  def update
    @project.attributes = project_params
    if @project.save
      respond_to do |format|
        format.html { redirect_to dashboard_path }
      end
    end
  end

  def add_owner
    new_owner = User.find(params[:user_id])
    if new_owner.can_create_project?
      pu = ProjectUser.find_by(project_id: @project.id, user_id: new_owner.id)
      pu.update_attribute(:rights, "owner")
      flash[:notice] = "Successfully added #{new_owner.name} as owner"
    else
      flash[:alert] = "#{new_owner.name} has reached their plan limit and cannot be added as an owner"
    end
    redirect_to edit_project_path(@project, anchor: "users")
  end

  def remove_owner
    remove_owner = User.find(params[:user_id])
    pu = ProjectUser.find_by(project_id: @project.id, user_id: remove_owner.id)
    pu.update_attribute(:rights, "member")
    redirect_to edit_project_path(@project, anchor: "users"), notice: "#{remove_owner.name} is now a regular member of the project"
  end

  def destroy
    if @project.destroy
      respond_to do |format|
        format.html { redirect_to dashboard_path }
      end
    end
  end

  def remove_user
    @user = User.find(params[:user_id])
    @project_user = ProjectUser.where(project_id: @project.id, user_id: @user.id)
    if @project_user.destroy
      respond_to do |format|
        format.html { redirect_to edit_project_path(@project, anchor: "users") }
      end
    end
  end

  def update_notifications
    @project.update_attribute(:email_notification, params[:project][:email_notification])
    if @project.notifications.any?
      @notification = @project.notifications.first
    else
      @notification = @project.notifications.build
    end

    if notification_params.values.reject(&:empty?).length == 0
      @notification.destroy
      notice = {notice: "Settings saved"}
    else
      @notification.attributes = notification_params
      notice = @notification.save ? {notice: "Notification Settings successfully saved"} : {alert: "Notification settings cannot be saved"}
    end

    respond_to do |format|
      format.html { redirect_to edit_project_path(@project, anchor: "notifications"), notice }
    end
  end

  # Move more of this to the model so it's easier to test.
  #  After verifying inclusion just update the attribute.
  def verify_script
    status = nil
    attr_changed = false
    begin
      if @project.script_present?
        attr_changed = true if @project.script_verified == false
        @project.update_attribute(:script_verified, true)
        flash[:notice] = "Script has been successfully verified"
        status = 200
      else
        flash[:notice] = "Could not verify the script at #{@project.url}."
        status = 400
      end
    rescue => e
      if e == SocketError
        flash[:notice] = "Cannot find website. Please make sure project URL is correct."
      else
        flash[:notice] = "Something went wrong."
      end
      status = 400
    end

    if status == 200 && attr_changed
      UserMailer.script_verification(current_user.email, @project.id.to_s).deliver
    end

    respond_to do |format|
      format.js {render json: {message: flash[:notice]}, status: status}
      format.html {redirect_to :back}
    end
  end

  def run
    test_run = @project.test_runs.build({user: current_user, platforms: params[:browsers], queued_at: Time.now})
    if test_run.save
      test_run.platforms.each do |p|
        browser_test = test_run.browser_tests.create!({browser: p.split('_').last,
                                              platform: p.split('_').first})
      end
      TestWorker.perform_async("queue_tests", "Project", test_run.id.to_s)
      respond_to do |format|
        format.html { redirect_to project_test_run_path(@project, test_run) }
        format.json { }
      end
    end
  end

  private

  def ensure_num_projects_limit
    if current_user.owned_projects.count >= current_user.plan.num_projects
      redirect_to :back, notice: "You have reached the max number of projects you can create. Upgrade your plan to get more projects."
    end
  end

  def project_params
    params.require(:project).permit(:name, :url, :basic_auth_username, :basic_auth_password)
  end

  def notification_params
    params.require(:notification).permit(:subdomain, :room_name, :token, :service)
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper

  def script_email_content(project)
    newline = "%0A"
    subject = "subject=Please add this JS Snippet so I can start GorillaTesting!"
    body = "body=Hello my smart friend -- I would like to start using GorillaTest to turn my testing frown upside down, and in order to do so I need you to insert the code below into the HEAD of the site to be tested. If you have any questions feel free to check out the documentation at https://www.gorillatest.com/documentation or email support@gorillatest.com."
    script = "<script src='#{ENV['API_URL']}/assets/recordv2.js' data-api-key='#{project.api_key}' data-project-id='#{project.id.to_s}'></script>"

    return "#{subject}#{newline}&#{body}#{newline}#{newline}CODE:#{newline}#{script}"
  end

  def link_to_record(project)
    if project.url.match(/\?\w*/)
      return project.url + "&gorilla-recording=true"
    else
      return project.url + "?gorilla-recording=true"
    end
  end

  def most_recent?(scenarios, scenario)
    scenarios.first == scenario
  end

  def most_recent_run(scenario)
    scenario.test_runs.sort_by(&:created_at).reverse.first
  end
end

app/views/projects/_embed_script_modal.html.haml
- content_for :head do
  %script
    :plain
      $(document).ready(function (){
        var clip = new ZeroClipboard($("#copy-embed-script-btn"))
        clip.on('complete', function(){
          $("#copy-confirmation").show().delay(1000).fadeOut("slow")
        })
      })

%div.modal.fade{id: "embed-modal-#{project.id}", class: 'embed-modal'}
  .modal-dialog
    .modal-content{style: "width: 700px;"}
      .modal-header
        - if project.script_verified? || show_buttons
          %button.close{data: {dismiss: "modal"}, aria:{hidden: true}} &times;
        %h4.modal-title Embed Code for #{project.name}
      .modal-body
        %p Insert the code below into the HEAD of the site to be tested. Click "Verify Embedded Script" to verify that the script has been placed on your website correctly.
        %br
        %blockquote#script-to-copy{style: "padding: 40px; margin: 1px solid #ccc; background: #eee; font-family: Menlo"}
          - if Rails.env.development?
            :plain
              &lt;script src="#{ENV['API_URL']}/assets/recordv2.js"<br />
              &nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;data-api-url="#{ENV['API_URL']}"<br />
              &nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;data-api-key="#{project.api_key}"<br >
              &nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;data-project-id="#{project.id}"&gt;&lt;/script&gt;
          - else
            :plain
              &lt;script src="#{ENV['API_URL']}/assets/recordv2.js"<br />
              &nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;data-api-key="#{project.api_key}"<br >
              &nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;data-project-id="#{project.id}"&gt;&lt;/script&gt;
      .modal-footer
        %a.btn.btn-success{href: "mailto:?#{script_email_content(project)}", target: "_blank"}
          %i.fa.fa-envelope
          Send Email
        %button.btn.btn-info#copy-embed-script-btn{data: {"clipboard-target" => "script-to-copy"}, title: "Click me to copy the script!"}
          %i.fa.fa-copy
          Copy Script
        =image_tag "icons/loading.gif", class: 'loading-gif', style: "display: none;"
        %a.btn.btn-info.verify-script-modal-button{href: "#{project_verify_script_path(project)}",project_link: "#{project_path(project)}"}
          %i.fa.fa-magic
          Verify Embedded Script
        - if project.script_verified? || show_buttons
          %button.btn.btn-info{data: {dismiss: "modal"}, aria: {hidden: true}} Close
        #copy-confirmation
          Copied! Go Bananas!

app/views/projects/_project_invitation_modal.html.haml
- content_for :head do
  = javascript_include_tag "invitations"
.modal.fade{id: "invite-users-to-project"}
  .modal-dialog
    .modal-content
      - if @project.has_invitations_left?
        .modal-header
          %button.close{data: {dismiss: "modal"}, aria:{hidden: true}} &times;
          %h1 Invite users to #{@project.name}
        .modal-body
          = simple_form_for User.new, :url => '/invitation', :html => {:method => :post, class: 'invite-modal-form smart-form'} do |f|
            = hidden_field_tag "project_id", @project.id
            = f.input :email, label: "Email (enter addresses separated by a comma)"
        .modal-footer
          =button_tag "Send Invitations", id: 'send-project-invitations', class: 'btn btn-primary'
          %p#sending-invitations{style: "display: none;"} Sending. Hang Tight...
      - else
        .modal-body
          %button.close{data: {dismiss: "modal"}, aria:{hidden: true}} &times;
          %br
          %b You have no more invitations left. Click #{link_to "here", change_plan_path} to upgrade your plan and invite more users to this project!

app/views/projects/_projects_header.html.haml
.row
  .col-sm-12
    .project-title#tour-project-show-overview#tour-project-show-start
      %h1#tour-now-your-turn
        = link_to @project.name, project_path(@project)
        - if params[:controller] == "test_runs"
          = " - "
          = link_to @scenario.name, project_test_test_runs_path(@project, @scenario.slug)
        - if @test_run
          %br
          %i.test-run-created-by
            created by: #{@test_run.user.name}
    .project-links
      - if params[:controller] == "test_runs" && params[:action] == "index"
        = link_to project_test_path(@project, @scenario), class: 'btn btn-warning', rel: "tooltip", title: "Watch Test Run Live", style: "margin-right: 12px;" do
          %i.fa.fa-video-camera
        = link_to project_test_path(@project, @scenario), class: 'btn btn-default delete-test-button', rel: "tooltip", title: "Delete Test", method: "delete", confirm: "Are You Sure?" do
          %i.fa.fa-trash-o
      .btn-group
        - if params[:controller] == "projects"
          = link_to edit_project_path(@project), "data-original-title" => "Mark Important", "data-placement" => "bottom", rel: "tooltip", title: "Settings", class: "project-setting-button btn btn-sm" do
            %strong
              %i.fa.fa-cog.fa-lg
          = link_to "#", "data-original-title" => "Move to folder", "data-placement" => "bottom", rel: "tooltip", title: "Invite", class: "project-setting-button btn btn-sm", data: {toggle: "modal", target: "#invite-users-to-project"} do
            %strong
              %i.fa.fa-user.fa-lg

app/views/projects/_scenarios.html.haml
.row{class: "scenario scenario_#{scenario.id}"}
  .col-sm-12
    .pull-right{style: "color: white;"}
      = play_button(scenario)
      = play_developer_mode_button(scenario)
    %h5{style: "display: inline;"}
      = link_to scenario.name, project_test_test_runs_path(@project, scenario.slug)
      - if scenario.all_test_runs.present?
        %table{style: "font-size: 1.0em"}
          %tr
            %th{style: "padding-right: 5px;"} Last Ran By:
            %td{style: "width: 200px;"}
              = gravatar_image_tag(scenario.all_test_runs.first.user, 16)
              = scenario.all_test_runs.first.user.name
            %th{style: "padding-right: 5px;"} Ran:
            %td{style: "width: 200px;"}
              #{distance_of_time_in_words_to_now(scenario.all_test_runs.first.created_at)} ago
            %th{style: "padding-right: 5px;"} Duration:
            %td= duration_to_hours_minutes_seconds(scenario.all_test_runs.first.duration)

  .row
    .col-sm-12{id: "test_run-#{scenario.id}"}
      %h4 Start A New Test Run
      = form_tag run_scenario_project_test_path(@project, scenario.id), class:"scenario-run", id: "scenario_#{scenario.id}" do
        .row
          .col-sm-4
            %h5 Windows
            %ul
              %li
                = check_box_tag "browsers[]", "windows_firefox"
                = image_tag('icons/firefox.png', alt: "Firefox")
                Firefox
              %li
                = check_box_tag "browsers[]", "windows_chrome"
                = image_tag('icons/chrome.png', alt: "Chrome")
                Chrome
              %li
                = check_box_tag "browsers[]", "windows_ie9"
                = image_tag('icons/ie.png', alt: "Internet Explorer 9")
                Internet Explorer 9
              %li
                = check_box_tag "browsers[]", "windows_ie10"
                = image_tag('icons/ie.png', alt: "Internet Explorer 10")
                Internet Explorer 10
              %li
                = check_box_tag "browsers[]", "windows_ie11"
                = image_tag('icons/ie.png', alt: "Internet Explorer 11")
                Internet Explorer 11
          .col-sm-4
            %h5 OS X
            %ul
              %li
                = check_box_tag "browsers[]", "mac_safari"
                = image_tag('icons/safari.png', alt: "Safari")
                Safari
              %li
                = check_box_tag "browsers[]", "mac_firefox"
                = image_tag('icons/firefox.png', alt: "Firefox")
                Firefox
              %li
                = check_box_tag "browsers[]", "mac_chrome"
                = image_tag('icons/chrome.png', alt: "Chrome")
                Chrome
          .col-sm-4
            %h5 Linux
            %ul
              %li
                = check_box_tag "browsers[]", "linux_firefox"
                = image_tag('icons/firefox.png', alt: "Firefox")
                Firefox
              %li
                = check_box_tag "browsers[]", "linux_chrome"
                = image_tag('icons/chrome.png', alt: "Chrome")
                Chrome

      .row
        .col-sm-12
          %span.hide.concurrency-warning
            Your plan only allows
            %span.concurrency-limit
              #{@concurrency_limit}
            concurrent browsers for a test run
          = submit_tag "Run Tests", class: "btn btn-primary run-test", disabled: true

app/views/projects/edit.html.haml
= render 'projects/projects_header'
.row
  .col-sm-12
    %ul.nav.nav-tabs
      %li.active
        %a{href: "#home", data: {toggle: "pill"}}
          %span.glyphicon.glyphicon-cog
          Project Info
      %li
        %a{href: "#users", data: {toggle: "pill"}, target: "users"}
          %span.glyphicon.glyphicon-user
          Users
      %li
        %a{href: "#notifications", data: {toggle: "pill"}, target: "notifications"}
          %span.glyphicon.glyphicon-bullhorn
          Notifications
      %li
        %a{href: "#delete", data: {toggle: "pill"}, target: "delete"}
          %span.glyphicon.glyphicon-remove
          Delete Project

    %div.tab-content.well
      #home.tab-pane.active
        %br
        = simple_form_for @project do |f|
          = f.input :name
          = f.input :url
          %br
          = link_to "Show Advanced Settings", "javascript:void();", id: "show_project_advanced_settings"
          = link_to "Hide Advanced Settings", "javascript:void()", id: "hide_project_advanced_settings", style: "display: none;"
          #advanced_settings{style: "display: none;"}
            %br
            %p Does your project have HTTP basic access authentication? If so enter the credentials below:
            = f.input :basic_auth_username
            = f.input :basic_auth_password
          %br
          %br
          .clearfix
          = f.submit "Save Project", class: "btn btn-info"
      #users.tab-pane
        %p
          -if @project.has_invitations_left?
            You can invite #{@project.num_invitations_remaining} more members to this project.
            %br
            Click #{link_to "here", invitations_path(project_id: @project.id.to_s)} to invite a member to this project.
          -else
            You can't invite any more people to this project.
        %p
          #{link_to 'Upgrade your plan', change_plan_path} to add more members to your project!
        %br
        .row
          .col-sm-12
            - @project.users.each do |user|
              %user_block{style: "float: left; width: 300px; background-color: #fff; margin-right: 10px; padding: 10px; border: 1px solid #ccc; margin-bottom: 10px;"}
                .pull-left{style: "margin-right: 10px; border: 1px solid #333;"}
                  = gravatar_image_tag(user, 48)
                - unless @project.owner?(user)
                  .pull-right
                    = link_to glyph('remove'), remove_user_project_path(@project, user.id), method: :post
                %span{style: "font-size: 1.6em; font-weight: bold;"}
                  - if user.encrypted_password.blank?
                    = truncate(user.email, length: 13)
                  - else
                    = user.name
                - if @project.owner?(user)
                  %span{style: "font-size: 1.2em"} (owner)
                - elsif user.encrypted_password.blank?
                  %span{style: "font-size: 1.2em"} (invited)
                - else
                  %span{style: "font-size: 1.2em"} (member)
                %br
                - unless user.encrypted_password.blank?
                  = user.email
                - if @project.owner?(current_user) && !@project.owner?(user) && current_user != user
                  .pull-right
                    = link_to "Make Owner", project_add_owner_path(@project, user.id), method: :put
                - if @project.owner?(current_user) && @project.owner?(user) && current_user != user
                  .pull-right
                    = link_to "Revoke Ownership", project_remove_owner_path(@project, user.id), method: :put

      #notifications.tab-pane
        %br
        =simple_form_for @notification, url: update_notifications_project_path(@project), method: :post do |f|
          %br
          %h3 Email Notifications
          -if @project.email_notification == "success"
            =radio_button_tag "project[email_notification]", "success", checked: true
            =label_tag "Send emails on test completion"
            %br
            =radio_button_tag "project[email_notification]", "fail"
            =label_tag "Send Emails only on test failure"
          -else
            =radio_button_tag "project[email_notification]", "success"
            =label_tag "Send Emails on success and failure"
            %br
            =radio_button_tag "project[email_notification]", "fail", checked: true
            =label_tag "Send Emails only on failure"
          %h3 Campfire
          =f.input :subdomain
          =f.input :token, label: "API Key"
          =f.input :room_name
          =f.input :service, as: :hidden, value: "campfire"
          =f.submit "Save Notification Settings", class: "btn btn-info"

      - if @project.owner?(current_user)
        #delete.tab-pane
          %div{style: "padding: 30px;"}
            %p Deleting this project will permanently destroy all tests and components related to this project. If you would like to continue, please click the "Delete Project" button below.
            = link_to raw("#{glyph('remove')} Delete Project"), project_path, class: "btn btn-danger", method: :delete, confirm: "Are you sure?"