config/routes.rb
Autotest::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  namespace :admin do
    resources :beta_invitations, only: [:index] do
      member do
        post 'invite'
      end
    end
  end

  get "/recorder" => "recorder#index"
  get "/developer" => "recorder#developer"


  namespace :heroku do
    resources :resources
    post '/sso/login' => "sso#create"
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount MailPreview => 'mail_view' if Rails.env.development?

  resources :scenarios
  resources :plans do
    member do
      get :upgrade
      post :upgrade
      post :downgrade
    end
  end
  resources :credit_cards, only: [:index, :create, :destroy], path: "credit-cards" do
    member do
      post :default
    end
  end
  resources :messages do
    member do
      post :mark_read
    end
    collection do
      post :mark_all_read
    end
  end

  post "/send-developer-emails" => "pages#send_developer_emails", as: "send_developer_emails"

  get "/tours" => "tours#show"
  put "/tours" => "tours#update"

  #application
  devise_for :users, controllers: {registrations: :registrations, sessions: :sessions, omniauth_callbacks: :omniauth_callbacks, passwords: :passwords}, skip: :invitations
  devise_scope :user do
    get "/login" => "sessions#new"
    get "/logout" => "sessions#destroy"
    get '/sign-up-free' => 'registrations#new', as: 'sign_up_free'
    get '/my-info' => 'registrations#edit', as: 'my_info'
    get '/change-your-plan' => 'registrations#change_plan', as: 'change_plan'
    post "/upgrade/:plan_id" => 'registrations#upgrade', as: 'upgrade'
    get '/upgrade/:plan_id' => "registrations#upgrade", as: "get_upgrade"
    get '/downgrade/:plan_id' => "registrations#downgrade", as: "get_downgrade"
    get '/manage-billing' => 'registrations#manage_billing', as: 'billing'
    get '/users/confirm' => "confirmations#show", as: 'confirmation'
    post '/cancel' => "registrations#cancel_user", as: "cancel"
  end

  get 'dashboard', to: "dashboard#index"

  as :user do
    get 'invitations', to: 'invitations#index', as: 'invitations'
    get 'invitation', to: "invitations#new", as: :new_invitation
    post 'invitation', to: "invitations#create"
    get 'invitation/accept', to: "invitations#edit", as: :accept_invitation
    put 'invitation/accept', to: "invitations#update", as: :complete_invitation
  end

  resources :projects do
    post 'remove_user/:user_id', to: 'projects#remove_user', on: :member, as: :remove_user
    post 'verify_script', to: 'projects#verify_script', as: :verify_script
    post 'update_notifications', to: "projects#update_notifications", on: :member, as: :update_notifications
    put 'add_owner/:user_id', to: 'projects#add_owner', as: :add_owner
    put 'remove_owner/:user_id', to: 'projects#remove_owner', as: :remove_owner
    post :run, on: :member
    resources :test_runs, controller: :project_test_runs, only: [:index, :show]
    resources :tests, controller: :scenarios do
      post :run, on: :member, as: "run_scenario"
      resources :steps
      resources :test_runs, only: [:index, :show]
    end
  end

  namespace :api do
    namespace :v1 do
      match '/scenarios' => "scenarios#create", via: :options
      match '/scenarios/:scenario_id' => "scenarios#show", via: :options
      match '/scenarios/:scenario_id/steps' => "steps#create", via: :options
      match '/scenarios/:scenario_id/publish' => "scenarios#publish", via: :options
      match '/scenarios/:scenario_id/publish' => "scenarios#publish", via: :post
      resources :scenarios do
        resources :steps
      end
    end

    namespace :dashing do
      match '/total_tests_run' => "dashboard#total_tests_run", via: :get
      match '/total_minutes' => "dashboard#total_minutes", via: :get
    end
  end

  #pages
  get 'faqs', to: 'pages#faqs'
  get 'pricing', to: 'pages#pricing'
  get 'documentation', to: 'pages#documentation'
  # get 'privacy', to: 'pages#privacy'
  get 'terms', to: 'pages#terms'
  get 'beta-invitation', to: 'pages#beta_invitation', as: 'beta_invitation'
  post 'create-beta-invitation', to: 'pages#create_beta_invitation', as: 'create_beta_invitation'
  post '/coupons/redeem', to: "coupons#redeem", as: "redeem_coupon"

  # Test Pages
  get '/test/index', to: "autotest#index"
  get '/test/form', to: "autotest#form", as: "test_form"
  post '/test/form_post', to: "autotest#form_post", as: "test_form_post"
  get '/test/thankyou', to: "autotest#thankyou", as: "test_thankyou"
  get '/test/terms', to: "autotest#terms", as: 'test_terms'

  root 'pages#welcome'
end

app/models/scenario.rb
class Scenario

  attr_accessor :driver

  include Mongoid::Document
  include Mongoid::Paranoia
  include Mongoid::Slug
  include Mongoid::Timestamps

  field :name, type: String
  field :window_x, type: Integer
  field :window_y, type: Integer
  field :start_url, type: String

  # for demoing playback with fake results
  field :demo, type: Boolean
  field :fail_browsers, type: String
  field :fail_step_num, type: Integer

  slug :name

  belongs_to :project

  embeds_many :steps

  has_many :test_runs, class_name: 'ScenarioTestRun'

  validates :name, presence: true, uniqueness: {conditions: -> { where(deleted_at: nil)}, scope: :project}
  validates :window_x, :window_y, presence: true

  def current_status
    if test_runs.present?
      test_runs.last.status
    else
      return "unran"
    end
  end

  def all_test_runs
    (test_runs + project.test_runs).select{|run| run.created_at > (created_at || steps.first.created_at)}.sort_by(&:created_at).reverse
  end

end

app/controllers/api/v1/scenarios_controller.rb
class Api::V1::ScenariosController < Api::V1::BaseController

  respond_to :json, :js

  # before_filter :find_feature

  def index
    @scenarios = current_project.scenarios
    render json: @scenarios, root: false
  end

  def show
    @scenario = current_project.scenarios.find(params[:id])
    render json: @scenario, root: false
  end

  def create
    @scenario = current_project.scenarios.new(scenario_params)
    if @scenario.save
      render json: @scenario, root: false
    else
      render json: {errors: @scenario.errors.to_a}.to_json, status: 400
    end
  end

  def update
    @scenario = current_project.scenario.find(params[:id])
    @scenario.attributes = scenario_attributes
    if @scenario.save
      render json: @scenario, root: false
    end
  end

  def publish
    @scenario = current_project.scenarios.find(params[:id])
    Pusher.trigger(["project-#{current_project.id.to_s}"],
                    "scenario_completed", {scenario_id: @scenario.id.to_s, project_id: current_project.id.to_s,
                                           scenario_name: @scenario.name, concurrency_limit: @scenario.project.creator.plan.concurrent_browsers})
    head :ok, type: "application/json"
  end

  private

  # Need to figure out how features work into scenarios
  # def find_feature
  #   @feature = current_project.features.find(params[:feature_id])
  # end

  def scenario_params
    params.require(:scenario).permit(:name, :url, :window_x, :window_y, :start_url)
  end

end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController

  before_filter :authenticate_user!
  before_filter :find_project
  before_filter :find_scenario, except: [:index, :new, :create]


  def show; end

  def destroy
    if @scenario.destroy
      respond_to do |format|
        format.html { redirect_to project_path(@project) }
      end
    end
  end

  def run
    test_run = @scenario.test_runs.build({user: current_user, platforms: params[:browsers], queued_at: Time.now})
    if test_run.save
      test_run.platforms.each do |p|
        browser_test = test_run.browser_tests.create!({browser: p.split('_').last,
                                                    platform: p.split('_').first})
      end
      unless @scenario.demo?
        TestWorker.perform_async("queue_tests", "Scenario", test_run.id.to_s)
      end

      respond_to do |format|
        format.html do
          redirect_path_args = @scenario.demo ? {test: "run"} : {}
          redirect_to project_test_test_run_path(@project, @scenario.slug, test_run, redirect_path_args)
        end
        format.json { }
      end
    end
  end

  private

  def scenario_params
    params.require(:scenario).permit(:name, :window_x, :window_y, :start_url)
  end

end

app/helpers/scenarios_helper.rb
module ScenariosHelper

  def play_developer_mode_button(scenario)
    url = developer_mode_url(scenario)
    html = link_to(raw("#{glyph_button('play', "Play Developer Mode")}"), url, class: "btn btn-success btn-xs", target: "_blank")
    return html.html_safe
  end

  def developer_mode_url(scenario)
    join_char = scenario.steps.first.text.include?("?") ? "&" : "?"
    "#{scenario.steps.first.text}#{join_char}developer=true&scenario_id=#{scenario.id.to_s}"
  end

end

app/views/scenarios/_email_to_developer_modal.html.haml
%div.modal.fade{id: "alert-dev-modal-#{test_id}-#{test_run.try(:id)}"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{data: {dismiss: "modal"}, aria:{hidden: true}} &times;
        %h3 Send Test Details to a Dev
      .modal-body
        %p In the email we'll send a link to the project, the test, the test results (if any) and even a direct link for them to watch the test run in developer mode
        = form_tag(send_developer_emails_path) do
          =hidden_field_tag "developer[test_id]", test_id
          -if test_run
            =hidden_field_tag "developer[type]", test_run.class.to_s
            =hidden_field_tag "developer[test_run_id]", test_run.id.to_s
          =label_tag "developer[emails]", "Enter emails separated by comma"
          %br
          =text_field_tag 'developer[emails]', nil, id: "dev_emails", class: "form-control"
          %br
      .modal-footer
        =button_tag "Send Emails", class: 'btn btn-primary send-emails-to-dev'
        %p#sending-emails-message{style: 'display: none;'}
          Sending emails. Hang Tight...

app/views/scenarios/_test_run.html.haml
.pull-right.view-test_run{style: "width: 80px; background-color: #ccc; height: 100%; padding-top: 20px; padding-bottom: 20px; padding-left: 25px;"}
  = link_to glyph("play", {style: "font-size: 1.8em;"}), project_test_test_run_path(@project, @scenario, test_run)
.test_run_details{style: "padding-left: 10px;"}
  %h3{style: "margin-top: 2px;"} Test Run ##{test_run.number}
  %table
    %tr
      %th{style: "padding-right: 5px;"} Ran By:
      %td{style: "width: 200px;"}
        = gravatar_image_tag(test_run.user, 16)
        = test_run.user.name
      %th{style: "padding-right: 5px;"} Ran:
      %td{style: "width: 200px;"}
        #{distance_of_time_in_words_to_now(test_run.created_at)} ago
      %th{style: "padding-right: 5px;"} Duration:
      %td= duration_to_hours_minutes_seconds(test_run.duration)

app/views/scenarios/show.html.haml
.page-content.blocky
  .container
    .pull-right
      = link_to glyph_button("remove", "Delete Test"), project_test_path(@project, @scenario.slug), class: "btn btn-danger", method: :delete, confirm: "Are you sure?"
    %ol.breadcrumb
      %li
        Projects
      %li
        = link_to @project.name, project_path(@project)
      %li.active
        = link_to @scenario.name, project_test_path(@project, @scenario.slug)

    %br
    %br
    - @scenario.test_runs.reverse.each do |test_run|
      - if test_run.status != nil
        .test_run{class: test_run.status}
          = render partial: 'test_run', locals: {test_run: test_run}
      - else
        .test_run
          = render partial: 'test_run', locals: {test_run: test_run}
        %br{style: "clear: both;"}